/** Minimal PDF generation using raw PDF spec — no external dependencies. */

const FONT_SIZE = {
	title: 18,
	section: 13,
	body: 9,
	meta: 8,
};

const COLORS = {
	black: "0 0 0",
	gray: "0.4 0.4 0.4",
	lightGray: "0.92 0.92 0.92",
	white: "1 1 1",
};

interface PdfCell {
	text: string;
	width: number;
	align?: "left" | "right";
}

interface PdfTable {
	headers: PdfCell[];
	rows: PdfCell[][];
}

interface PdfReport {
	companyName: string;
	title: string;
	dateRange: string;
	generatedAt: string;
	summary: { label: string; value: string }[];
	table: PdfTable;
}

/**
 * Generates a clean PDF report as a Buffer.
 * Uses raw PDF stream commands for zero-dependency generation.
 */
export function generatePdfReport(report: PdfReport): Buffer {
	const pageWidth = 595; // A4
	const pageHeight = 842;
	const margin = 50;
	const contentWidth = pageWidth - margin * 2;
	let y = pageHeight - margin;

	const lines: string[] = [];

	function addText(
		text: string,
		x: number,
		yPos: number,
		size: number,
		color = COLORS.black,
	) {
		const escaped = text
			.replace(/\\/g, "\\\\")
			.replace(/\(/g, "\\(")
			.replace(/\)/g, "\\)");
		lines.push(`BT`);
		lines.push(`${color} rg`);
		lines.push(`/F1 ${size} Tf`);
		lines.push(`${x} ${yPos} Td`);
		lines.push(`(${escaped}) Tj`);
		lines.push(`ET`);
	}

	function addRect(
		x: number,
		yPos: number,
		w: number,
		h: number,
		color: string,
	) {
		lines.push(`${color} rg`);
		lines.push(`${x} ${yPos} ${w} ${h} re f`);
	}

	function addLine(
		x1: number,
		y1: number,
		x2: number,
		y2: number,
		color = COLORS.gray,
	) {
		lines.push(`${color} RG`);
		lines.push(`0.5 w`);
		lines.push(`${x1} ${y1} m ${x2} ${y2} l S`);
	}

	// ── Header ──
	addText(report.companyName, margin, y, FONT_SIZE.title);
	y -= 22;
	addText(report.title, margin, y, FONT_SIZE.section, COLORS.gray);
	y -= 16;
	addText(`Period: ${report.dateRange}`, margin, y, FONT_SIZE.meta, COLORS.gray);
	addText(
		`Generated: ${report.generatedAt}`,
		pageWidth - margin - 160,
		y,
		FONT_SIZE.meta,
		COLORS.gray,
	);
	y -= 8;
	addLine(margin, y, pageWidth - margin, y);
	y -= 20;

	// ── Summary Section ──
	addText("Summary", margin, y, FONT_SIZE.section);
	y -= 18;

	for (const item of report.summary) {
		addText(item.label, margin, y, FONT_SIZE.body, COLORS.gray);
		addText(item.value, margin + 180, y, FONT_SIZE.body);
		y -= 14;
	}
	y -= 10;
	addLine(margin, y, pageWidth - margin, y);
	y -= 20;

	// ── Data Table ──
	const table = report.table;

	// Header row background
	addRect(margin, y - 2, contentWidth, 16, COLORS.lightGray);

	let xPos = margin + 4;
	for (const header of table.headers) {
		addText(header.text, xPos, y, FONT_SIZE.body);
		xPos += header.width;
	}
	y -= 18;

	// Data rows
	for (let rowIdx = 0; rowIdx < table.rows.length; rowIdx++) {
		if (y < margin + 40) {
			// Would need pagination — truncate for now
			addText("... continued on next page", margin, y, FONT_SIZE.meta, COLORS.gray);
			break;
		}

		const row = table.rows[rowIdx];

		// Zebra striping
		if (rowIdx % 2 === 1) {
			addRect(margin, y - 2, contentWidth, 14, "0.97 0.97 0.97");
		}

		xPos = margin + 4;
		for (const cell of row) {
			const displayText =
				cell.text.length > Math.floor(cell.width / 5)
					? `${cell.text.substring(0, Math.floor(cell.width / 5) - 2)}..`
					: cell.text;
			addText(displayText, xPos, y, FONT_SIZE.body);
			xPos += cell.width;
		}
		y -= 14;
	}

	// ── Footer ──
	y = margin;
	addLine(margin, y + 10, pageWidth - margin, y + 10, COLORS.lightGray);
	addText("Generated by Zendak", margin, y - 4, FONT_SIZE.meta, COLORS.gray);
	addText(
		"Page 1",
		pageWidth - margin - 30,
		y - 4,
		FONT_SIZE.meta,
		COLORS.gray,
	);

	// ── Build PDF ──
	const stream = lines.join("\n");
	const streamBytes = Buffer.from(stream, "utf-8");

	const objects: string[] = [];
	let objCount = 0;

	function addObj(content: string): number {
		objCount++;
		objects.push(`${objCount} 0 obj\n${content}\nendobj`);
		return objCount;
	}

	// Catalog
	addObj(`<< /Type /Catalog /Pages 2 0 R >>`);
	// Pages
	addObj(
		`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,
	);
	// Page
	addObj(
		`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>`,
	);
	// Stream
	addObj(
		`<< /Length ${streamBytes.length} >>\nstream\n${stream}\nendstream`,
	);
	// Font
	addObj(
		`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,
	);

	const offsets: number[] = [];
	let pdf = "%PDF-1.4\n";
	for (const obj of objects) {
		offsets.push(Buffer.byteLength(pdf, "utf-8"));
		pdf += `${obj}\n`;
	}

	const xrefOffset = Buffer.byteLength(pdf, "utf-8");
	pdf += `xref\n0 ${objCount + 1}\n`;
	pdf += `0000000000 65535 f \n`;
	for (const offset of offsets) {
		pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
	}

	pdf += `trailer\n<< /Size ${objCount + 1} /Root 1 0 R >>\n`;
	pdf += `startxref\n${xrefOffset}\n%%EOF`;

	return Buffer.from(pdf, "utf-8");
}
